server:
  port: 8081

spring:
  dubbo:
    application:
      name: consumer
    registry:
      address: zookeeper://localhost
      port: 2181
    scan: com.edu.nchu.controller   #扫描需要暴露的服务
  servlet:
    multipart:
      max-file-size:
        3MB
      max-request-size:
        3MB
  thymeleaf:
    cache: false
    encoding: UTF-8