server:
  port: 8081

spring:
  dubbo:
    application:
      name: springboot-dubbo-demo
    registry:
      address: zookeeper://localhost
      port: 2181
    scan: com.edu.nchu.controller   #扫描需要暴露的服务
  thymeleaf:
    cache: false