server:
  port: 12306
spring:
  dubbo:
    application:
      name: provider #应用名
    registry:
      address: zookeeper://localhost #zookeeper地址
      port: 2181 #提供注册的端口
    protocol:
      name: dubbo
      port: 20890 #dubbo服务暴露的端口
    scan: com.edu.nchu.service #扫描的包名
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/personal_accounting?serverTimezone=Asia/Shanghai
    username: root
    password: guofofu
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations:
    - classpath*:mapperXml/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true